#!/usr/bin/env node
import inquirer from "inquirer";
import chalk from "chalk";
import chalkAnimation from "chalk-animation";
// Stop the welcome title
const sleep = () => new Promise((res, rej) => setTimeout(res, 1000));
// Create the welcome title
async function welcome_title() {
    console.clear();
    const title = chalkAnimation.rainbow("  ___ Let's Start Number Guessing Game ___");
    await sleep();
    title.stop();
}
welcome_title();
let life = 3;
async function askQuestion() {
    const autoGenerated = Math.floor(Math.random() * 10 + 1);
    // console.log(autoGenerated);
    do {
        life--;
        console.log(chalk.rgb(255, 120, 220)(`Player Life Left:${life}`));
        var ans = await inquirer
            .prompt([
                {
                    type: "input",
                    name: "user_ans",
                    message: chalk.inverse("Please Select any Number between 1 - 10 : "),
                    validate: (value) => {
                        if (isNaN(value)) {
                            return chalk.red("Please enter a valid number to perform this oprtation");
                        }
                        return true;
                    }
                }
            ]);
        if (ans.user_ans == autoGenerated) {
            console.log(chalk.green("Congratulations !!! You guess the right number."));
        }
        else if (ans.user_ans < autoGenerated) {
            console.log(chalk.red(`Your Number ${ans.user_ans} is less than guess number ${autoGenerated}.`));
        }
        else if (ans.user_ans > autoGenerated) {
            console.log(chalk.red(`Your Number ${ans.user_ans} is greater than guess number ${autoGenerated}.`));
        }
    } while (life > 0 && life !== ans.user_ans);
    if (life == 0 && autoGenerated !== ans.user_ans) {
        console.log(chalk.redBright(`GAME OVER !!!`));
    }
}
// askQuestion();
async function do_again() {
    do {
        console.clear();
        await welcome_title();
        life = 3;
        await askQuestion();
        var again_get_choice = await inquirer
            .prompt({
                type: "input",
                name: "restart",
                message: "Do you want to restart the game? Press 'y' or 'n' : "
            });
    } while (again_get_choice.restart == 'y' || again_get_choice.restart == 'Y' || again_get_choice.restart == 'yes' || again_get_choice.restart == 'YES' || again_get_choice.restart == 'Yes');
    console.log("\n                    _____________________ Thanks For Playing Game _____________________");
}
do_again();
